# Generated by Django 6.0 on 2026-04-26 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expert',
            name='bio',
            field=models.TextField(blank=True, verbose_name='О себе'),
        ),
        migrations.AlterField(
            model_name='expert',
            name='experience',
            field=models.IntegerField(blank=True, null=True, verbose_name='Опыт работы (лет)'),
        ),
        migrations.AlterField(
            model_name='expert',
            name='specialty',
            field=models.CharField(blank=True, choices=[('ethical_hacking', 'Этичный хакинг'), ('pentest', 'Пентест'), ('forensics', 'Цифровая криминалистика'), ('malware', 'Анализ вредоносного ПО'), ('network', 'Сетевая безопасность'), ('web_security', 'Веб-безопасность')], max_length=50, null=True),
        ),
    ]
